export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_ERROR = "LOGIN_ERROR";
//deparment
export const GETS_DEPARTMENTS_SUCCESS = 'GETS_DEPARTMENTS_SUCCESS';
export const GETS_DEPARTMENTS_ERROR = 'GETS_DEPARTMENTS_ERROR';

export const CREATE_DEPARTMENT_SUCCESS = 'CREATE_DEPARTMENT_SUCCESS';
export const CREATE_DEPARTMENT_ERROR = 'CREATE_DEPARTMENT_ERROR';


export const DELETE_DEPARTMENT_SUCCESS = 'DELETE_DEPARTMENT_SUCCESS';
export const DELETE_DEPARTMENT_ERROR = 'DELETE_DEPARTMENT_ERROR';

export const UPDATE_DEPARTMENT_SUCCESS = 'UPDATE_DEPARTMENT_SUCCESS';
export const UPDATE_DEPARTMENT_ERROR = 'UPDATE_DEPARTMENT_ERROR';

export const GET_DEPARTMENT_SUCCESS = 'GET_DEPARTMENT_SUCCESS';
export const GET_DEPARTMENT_ERROR = 'GET_DEPARTMENT_ERROR';

export const GET_INITIAL_STATE = 'GET_INITIAL_STATE';